### ISSUE TITLE
Lions Gate Entertainment (LGF)

### ISSUE THREAD

**Issue by ghost** [hellno/numerai-signals-tickermap#1]
Original: LGF.A, LGF/A US ,LGF-A.TO
Corrected: LGF.A ,LGF/A US, LGF-A
Note: Drop .TO suffix from the ticker

Original: LGF.B, LGF/B US, LFG-B.To
Corrected: LGF.B, LGF/B US, LGF-B
Note: Drop .TO suffix from ticker and correct Yahoo spelling (LFG to LGF)

**Comment by hellno** [comment]
thanks for reporting these errors :)
new logic provided by arbitrage fixed them.

new ticker_map.csv now has the following tickers:

bloomberg | yahoo | alpha_vantage
-- | -- | -- 
LGF/A US | LGF-A.TO | LGF-A
LGF/B US | LFG-B.To | LGF-B
