### ISSUE TITLE
full mapping completed

### ISSUE THREAD

**Issue by jonrtaylor** [hellno/numerai-signals-tickermap#2]
I've mapped bloomberg to Alpha Vantage using the following code:

`napi = numerapi.SignalsAPI(NAPI_PUBLIC_KEY, NAPI_PRIVATE_KEY)`
`eligible_tickers = pd.DataFrame(napi.ticker_universe())`
`eligible_tickers.columns = ['bloomberg_ticker']`
`eligible_tickers = eligible_tickers.iloc[1:, :].copy()`
`eligible_tickers['ticker'] = eligible_tickers.bloomberg_ticker.str[:-3]`

`reduced_tickers = eligible_tickers[(eligible_tickers.bloomberg_ticker.str.contains(" PW") == False)&\`
`     (eligible_tickers.bloomberg_ticker.str.contains(" CP") == False)&\`
`     (eligible_tickers.bloomberg_ticker.str.contains(" TB") == False)&\`
`     (eligible_tickers.bloomberg_ticker.str.contains(" HB") == False)&\`
`     (eligible_tickers.bloomberg_ticker.str.contains(" IT") == False)&\`
`     (eligible_tickers.bloomberg_ticker.str.contains(" ID") == False)&\`
`     (eligible_tickers.bloomberg_ticker.str.contains(" PM") == False)&\`
`     (eligible_tickers.bloomberg_ticker.str.contains(" SP") == False)&\`
`     (eligible_tickers.bloomberg_ticker.str.contains(" FH") == False)&\`
`     (eligible_tickers.bloomberg_ticker.str.contains(" AV") == False)&\`
`     (eligible_tickers.bloomberg_ticker.str.contains(" GA") == False)&\`
`     (eligible_tickers.bloomberg_ticker.str.contains(" DC") == False)&\`
`     (eligible_tickers.bloomberg_ticker.str.contains(" NZ") == False)&\`
`     (eligible_tickers.bloomberg_ticker.str.contains(" TI") == False)&\`
`     (eligible_tickers.bloomberg_ticker.str.contains(" NO") == False)&\`
`     (eligible_tickers.bloomberg_ticker.str.contains(" SM") == False)&\`
`     (eligible_tickers.bloomberg_ticker.str.contains(" IJ") == False)&\`
`     (eligible_tickers.bloomberg_ticker.str.contains(" MF") == False)&\`
`     (eligible_tickers.bloomberg_ticker.str.contains(" SJ") == False)&\`
`     (eligible_tickers.bloomberg_ticker.str.contains(" AU") == False)&\`
`     (eligible_tickers.bloomberg_ticker.str.contains(" SW") == False)&\`
`     (eligible_tickers.bloomberg_ticker.str.contains(" SS") == False)&\`
`     (eligible_tickers.bloomberg_ticker.str.contains(" KS") == False)&\`
`     (eligible_tickers.bloomberg_ticker.str.contains(" MK") == False)&\`
`     (eligible_tickers.bloomberg_ticker.str.contains(" IM") == False)&\`
`     (eligible_tickers.bloomberg_ticker.str.contains(" JP") == False)&\`
`     (eligible_tickers.bloomberg_ticker.str.contains(" TT") == False)&\`
`     (eligible_tickers.bloomberg_ticker.str.contains(" HK") == False)].copy()`
`reduced_tickers['av_ticker'] = 1`
`reduced_tickers['av_ticker'] = np.where(reduced_tickers.bloomberg_ticker.str.contains(" US"), reduced_tickers.ticker,`
`                                        np.where(reduced_tickers.bloomberg_ticker.str.contains(" NA"), reduced_tickers.ticker + ".AMS",`
`                                                 np.where(reduced_tickers.bloomberg_ticker.str.contains(" CA"), reduced_tickers.ticker + ".TRT",`
`                                                          np.where(reduced_tickers.bloomberg_ticker.str.contains(" BB"), reduced_tickers.ticker + ".BRU",`
`                                                                   np.where(reduced_tickers.bloomberg_ticker.str.contains(" FP"), reduced_tickers.ticker + ".PAR",`
`                                                                            np.where(reduced_tickers.bloomberg_ticker.str.contains(" GR"), reduced_tickers.ticker + ".DEX",`
`                                                                                     np.where(reduced_tickers.bloomberg_ticker.str.contains(" PL"), reduced_tickers.ticker + ".LIS",`
`                                                                                              np.where(reduced_tickers.bloomberg_ticker.str.contains(" LN"), reduced_tickers.ticker + ".LON",`
`                                                                                                       np.where(reduced_tickers.bloomberg_ticker.str.contains(" BZ"), reduced_tickers.ticker + ".SAO", reduced_tickers.av_ticker)))))))))`
`reduced_tickers['av_ticker'] = np.where(reduced_tickers.av_ticker.str.endswith("/A.LON"), reduced_tickers.av_ticker.str.replace("/", "-"), reduced_tickers.av_ticker)`
`reduced_tickers['av_ticker'] = np.where(reduced_tickers.av_ticker.str.endswith("LON"), reduced_tickers.av_ticker.str.replace("/", ""), reduced_tickers.av_ticker)`
`reduced_tickers['av_ticker'] = np.where(reduced_tickers.av_ticker.str.endswith("LON"), reduced_tickers.av_ticker.str.replace("*", ""), reduced_tickers.av_ticker)`
`reduced_tickers['av_ticker'] = reduced_tickers.av_ticker.str.replace("/", "-")`
`####ticker name changes should be handled by NUMERAI prior to releasing the weekly eligible ticker list####`

**Comment by jonrtaylor** [comment]
code formatted horrendously... apologies. LMK if you want me to post a .py file for you.

**Comment by hellno** [comment]
thanks for the amazing effort! just merged it
